name: my-ts-node-template
on: [push]
jobs:
  preload-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
      - run: npm ci
  lint:
    runs-on: ubuntu-latest
    needs: [preload-npm]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
      - run: |
          npm ci
          npm run lint
  test:
    runs-on: ubuntu-latest
    needs: [preload-npm]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
      - run: |
          npm ci
          npm run coverage
  security:
    runs-on: ubuntu-latest
    needs: [preload-npm]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
      - run: |
          npm ci
          npm audit
